### ISSUE TITLE
No buttons when uGUIToolbal folder isn't root folder.

### ISSUE THREAD

**Issue by uvivagabond** [baba-s/ugui-toorbar#1]
![ugui](https://user-images.githubusercontent.com/20247639/36706082-83ed6c5a-1b68-11e8-946f-52a41934954b.png)
Tool only work when main folder is root folder.
Here is a problem.
uGUIToolbarSettings scriptableObject is always loaded from same Path.
![problem](https://user-images.githubusercontent.com/20247639/36706143-c9eb8c6e-1b68-11e8-936a-5097fb9bd2cd.png)
So it's same problem like with projectSettingsToolbar.

**Comment by baba-s** [comment]
I fixed this problem as follows, Thank you!

```cs
private string m_dir;

..

private uGUIToolbarSettings Settings
{
    get { return m_settings ?? ( m_settings = 
        AssetDatabase.LoadAssetAtPath<uGUIToolbarSettings>( m_dir + "/uGUIToolbarSettings.asset" ) ); }
}

...

private void OnEnable()
{
    var mono = MonoScript.FromScriptableObject( this );
    var path = AssetDatabase.GetAssetPath( mono );
    m_dir = Path.GetDirectoryName( path );
}
```
